name: Content Production Request
description: Standard template for content production requests.
title: 'Title: [Enter the title of the article]'
labels: ['content', 'production']

body:
  - type: markdown
    attributes:
      value: |
        ### Content Production Request

  - type: select
    id: content_type
    attributes:
      label: Content Type
      description: Select the type of content you are requesting.
      options:
        - Article
        - Guide

  - type: textarea
    id: description
    attributes:
      label: Article Description
      description: Provide a detailed description of the article. What is the main topic? What points should be covered? What is the objective of this article?
      placeholder: 'Describe the content topic and main points.'

  - type: input
    id: target_audience
    attributes:
      label: Target Audience
      description: Describe who the target audience is. Age, profession, interests, etc.
      placeholder: 'e.g., Digital Marketers, Small Business Owners, etc.'

  - type: textarea
    id: references
    attributes:
      label: References/Resources
      description: Include any references or resources that should be used or cited in the article
      placeholder: 'List any important resources or references.'

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of similar articles or content for reference
      placeholder: 'Include links or titles of similar content.'

  - type: textarea
    id: special_instructions
    attributes:
      label: Special Instructions
      description: Any additional notes or instructions for the content writer
      placeholder: 'Provide any additional information or special instructions.'